services:
  nginx:
    container_name: nginx
    build: .
    ports:
      - "80:80"
    restart: always
    networks:
      - expenses-network

networks:
  expenses-network:
    name: expenses-backend-network
    external: true